USE [master]
GO

/****** Object:  Database [papema]    Script Date: 19/07/2020 10:29:15 p. m. ******/
CREATE DATABASE [papema]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'papema', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\papema.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'papema_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\papema_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [papema].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [papema] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [papema] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [papema] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [papema] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [papema] SET ARITHABORT OFF 
GO

ALTER DATABASE [papema] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [papema] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [papema] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [papema] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [papema] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [papema] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [papema] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [papema] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [papema] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [papema] SET  DISABLE_BROKER 
GO

ALTER DATABASE [papema] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [papema] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [papema] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [papema] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [papema] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [papema] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [papema] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [papema] SET RECOVERY FULL 
GO

ALTER DATABASE [papema] SET  MULTI_USER 
GO

ALTER DATABASE [papema] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [papema] SET DB_CHAINING OFF 
GO

ALTER DATABASE [papema] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [papema] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [papema] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [papema] SET QUERY_STORE = OFF
GO

ALTER DATABASE [papema] SET  READ_WRITE 
GO

